name: "Pre-commit autoupdate"
description: "Runs pre-commit autoupdate"
author: "Galen Rice"
inputs:
  token:
    description: "The token that the action will use to create and update the pull request."
    default: ${{ github.token }}
  python_version:
    description: "Python version to use."
    default: "3.14"
  pre_commit_version:
    description: "Pre-commit version to use."
    default: "4.5.0"
  path_to_config:
    description: "Relative path to the .pre-commit-config.yaml file"
    default: ".pre-commit-config.yaml"
  commit_message:
    description: "Message to use for the generated commit"
    default: "ci: pre-commit autoupdate"
  pr_title:
    description: "Title of the PR to create."
    default: "pre-commit autoupdate"
  pr_branch_name:
    description: "Name of the branch to create with the update PR."
    default: "ci/pre-commit-autoupdate"
  create_as_draft:
    description: "Whether to open the update PR in draft mode"
    default: "false"
  pr_labels:
    description: "Comma or newline separated list of labels to add to the pull request"
    required: false
  pr_assignees:
    description: "Comma or newline separated list of GitHub usernames to assign to the pull request"
    required: false
  pr_reviewers:
    description: "Comma or newline separated list of GitHub usernames to request reviews from"
    required: false
  pr_team_reviewers:
    description: "Comma or newline separated list of GitHub team slugs to request reviews from"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Set temp filename for PR body"
      run: echo "TEMP_FILENAME=temp-pr-body-${{ github.run_id }}-${{ github.run_attempt }}.md" >> $GITHUB_ENV
      shell: bash

    - name: "Setup Python"
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python_version }}

    - name: "Install pre-commit"
      run: python -m pip install pre-commit==${{ inputs.pre_commit_version }}
      shell: bash

    - name: "Run pre-commit autoupdate"
      id: autoupdate-run
      run: |
        UPDATE_OUTPUT=$(pre-commit autoupdate)
        echo "$UPDATE_OUTPUT" \
          | sed -rn 's|^(.*updating.*)$|* \1|p' \
          | sed -rn 's|^\* \[(https://github.com/(.*))\] (.*)|* [\2](\1) - \3|p' \
          > ${{ env.TEMP_FILENAME }}
      shell: bash

    - name: "Read temp file contents for commit message"
      # Adds a multiline string to COMMIT_MESSAGE.
      # See: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#example-of-a-multiline-string
      run: |
        if [ -f "${{ env.TEMP_FILENAME }}" ]; then
          {
            echo 'COMMIT_MESSAGE<<EOF'
            echo "${{ inputs.commit_message }}"
            echo ''
            cat ${{ env.TEMP_FILENAME }}
            echo 'EOF'
          } >> "$GITHUB_ENV"
        else
          echo "COMMIT_MESSAGE=${{ inputs.commit_message }}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: "Create PR for updates"
      id: create-pr
      uses: peter-evans/create-pull-request@v8
      with:
        token: ${{ inputs.token }}
        branch: ${{ inputs.pr_branch_name }}
        title: ${{ inputs.pr_title }}
        # Use the body of our temp file for the body of the PR
        body-path: ${{ env.TEMP_FILENAME }}
        # start in draft, so that I can manually un-draft it,
        # in order to trigger CI runs
        # See: https://github.com/peter-evans/create-pull-request/issues/48
        draft: ${{ inputs.create_as_draft == 'true' }}
        # Only interested in updates to pre-commit config
        commit-message: ${{ env.COMMIT_MESSAGE }}
        add-paths: |
          ${{ inputs.path_to_config }}
        labels: ${{ inputs.pr_labels }}
        assignees: ${{ inputs.pr_assignees }}
        reviewers: ${{ inputs.pr_reviewers }}
        team-reviewers: ${{ inputs.pr_team_reviewers }}

    - name: "PR created"
      if: ${{ steps.create-pr.outputs.pull-request-number }}
      run: |
        ACTION="${{ steps.create-pr.outputs.pull-request-operation }}"
        if [ "$ACTION" == "none" ]; then
          ACTION="unchanged"
        fi
        PR_NUMBER="${{ steps.create-pr.outputs.pull-request-number }}"
        PR_URL="${{ steps.create-pr.outputs.pull-request-url }}"
        echo "PR ${ACTION}: [#${PR_NUMBER}](${PR_URL})" >> $GITHUB_STEP_SUMMARY
      shell: bash

branding:
  icon: "refresh-cw"
  color: "orange"
