# Run pre-commit autoupdate and create a pull request with any updates

name: pre-commit autoupdate

on:
  workflow_dispatch:
  schedule:
    # Every Monday 11AM UTC (~6AM US/Eastern)
    - cron: "0 11 * * 1"

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # When dogfooding ourselves, target main branch to avoid chasing tags
      - uses: griceturrble/precommit-autoupdate-action@main
        with:
          create_as_draft: true
